image: "muhq/python-dev:0.1"

before_script:
  - python --version
  - pipenv install --dev

stages:
  - Static Analysis

pylint:
  stage: Static Analysis
  script:
    - pipenv run make check-pylint

format:
  stage: Static Analysis
  script:
    - pipenv run make check-format

mypy:
  stage: Static Analysis
  script:
    - pipenv run make check-mypy
